apiVersion: v1
kind: Service
metadata:
  name: k8s-dev-dashboard
  labels:
    app: k8s-dev-dashboard
spec:
  ports:
  - port: 80
    targetPort: http
  selector:
    app: k8s-dev-dashboard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-dev-dashboard
spec:
  selector:
    matchLabels:
      app: k8s-dev-dashboard
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-dev-dashboard
    spec:
      serviceAccountName: k8s-dev-dashboard
      containers:
      - name: api
        image: gitcommit/k8s-dev-dashboard-api:v0.0.2
        env:
         - name: APPLICATION_NAMESPACES
           value: integration,validation,preproduction,production
         - name: ARBITRARY_ROLLING_UPDATE_NAMESPACES
           value: integration,validation
        resources:
          limits:
            memory: 50M
          requests:
            memory: 50M
        readinessProbe:
          httpGet:
            path: /health
            port: api
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: api
          initialDelaySeconds: 5
          periodSeconds: 30
        ports:
        - name: api
          containerPort: 3000
      - name: front
        image: gitcommit/k8s-dev-dashboard-front:v0.0.3
        resources:
          limits:
            memory: 50M
          requests:
            memory: 50M
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 30
        ports:
        - name: http
          containerPort: 3000
