apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-dev-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: k8s-dev-dashboard-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
      - events
      - nodes
    verbs:
      - list
      - get
  - apiGroups:
      - "apps"
    resources:
      - replicasets
    verbs:
      - get
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - get
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8s-dev-dashboard-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-dev-dashboard-cluster-role
subjects:
  - kind: ServiceAccount
    name: k8s-dev-dashboard
    namespace: default
